#!/bin/bash
# Start Imogen at system startup

JUCE_PLUGIN_PATH=/udata/elk-examples/plugins/elk_juce_example.so

if ! test -f "$JUCE_PLUGIN_PATH"; then
    echo "Error -- Imogen not found"
    exit 0
fi

MIDI_KEYBOARD="$(aconnect -l)"
if ! echo "$MIDI_KEYBOARD" | grep -q "16"; then
    echo "Error! Midi Keyboard not connected. Please connect one, Imogen depends on it."
    exit 0
fi

stop
sleep 1

sudo systemctl start sensei
sleep 1

sushi -r  --multicore-processing=2 -c ./config_imogen.json &
sleep 1

main_app &
sleep 3
aconnect -x
aconnect 16 128